# frozen_string_literal: true

module SolidusAuthorizenet
  ##
  # Gateway
  #
  # This gateway is intended to bridge Solidus and AuthorizeNet API. It handles
  # creation of customers, authorizarion of payments, voiding and refunding.
  #
  # If a customer is already created inside authorize net with same email/merchantCustomerId
  # then that customer is reused.
  class Gateway
    ##
    # Init
    #
    # Inits the gateway with provided gateway options (those set in admin)
    def initialize(options)
      @options = options
    end

    ##
    # Client
    #
    # Returns an AuthorizeNet client configured to either sandbox or production
    # environment
    def client
      ::AuthorizeNet::API::Transaction.new(@options[:api_login_id],
                                           @options[:api_transaction_key],
                                           gateway: @options[:test_mode] ? :sandbox : :production)
    end

    ##
    # Get Customer
    #
    # Requests a customer using an authorize.net customer id. Returns info about
    # the customer and their payment profiles.
    def get_customer(customer_profile_id)
      request = ::AuthorizeNet::API::GetCustomerProfileRequest.new
      request.customerProfileId = customer_profile_id

      response = client.get_customer_profile(request)
      success = response.messages.resultCode == ::AuthorizeNet::API::MessageTypeEnum::Ok

      log_response(:get_customer, response)

      return nil unless success

      payment_profiles = []
      response.profile.paymentProfiles.each do |payment_profile|
        payment_profiles << {
          id: payment_profile.customerPaymentProfileId
        }
      end

      {
        id: request.customerProfileId,
        user_id: response.profile.merchantCustomerId,
        payment_profiles: payment_profiles
      }
    end

    ##
    # Create Customer
    #
    # Creates a customer and a payment profile in authorize.net. Returns
    # customer id.
    def create_customer(payment)
      log(:create_customer, "Creating customer for #{payment.order.id}")
      order = payment.order
      billing_address = order.bill_address
      shipping_address = order.ship_address
      email = order.user&.email || order.email
      user_id = order.user&.id || "guest-#{order.id}"

      payment_profile = ::AuthorizeNet::API::CustomerPaymentProfileType.new
      payment_profile.payment = ::AuthorizeNet::API::PaymentType.new
      payment_profile.payment.opaqueData = ::AuthorizeNet::API::OpaqueDataType.new(payment.source.data_descriptor,
                                                                                   payment.source.data_value)

      bill_to = ::AuthorizeNet::API::CustomerAddressType.new
      bill_to.firstName = billing_address.name.split('').first
      bill_to.lastName = billing_address.name.split('').last || bill_to.firstName
      bill_to.address = billing_address.address1
      bill_to.city = billing_address.city
      bill_to.state = billing_address.state.abbr if billing_address.state
      bill_to.zip = billing_address.zipcode
      bill_to.country = billing_address.country.iso if billing_address.country
      bill_to.phoneNumber = billing_address.phone

      payment_profile.billTo = bill_to

      request = ::AuthorizeNet::API::CreateCustomerProfileRequest.new

      request.profile = ::AuthorizeNet::API::CustomerProfileType.new
      request.profile.merchantCustomerId = user_id
      request.profile.email = email
      request.profile.description = "Generated by order #{order.id}"

      request.profile.paymentProfiles = [payment_profile]

      if shipping_address
        ship_to = ::AuthorizeNet::API::CustomerAddressType.new
        ship_to.firstName = shipping_address.name.split('').first
        ship_to.lastName = shipping_address.name.split('').last || ship_to.firstName
        ship_to.address = shipping_address.address1
        ship_to.city = shipping_address.city
        ship_to.state = shipping_address.state.abbr if shipping_address.state
        ship_to.zip = shipping_address.zipcode
        ship_to.country = shipping_address.country.iso if shipping_address.country
        ship_to.phoneNumber = shipping_address.phone

        request.profile.shipToList = [ship_to]
      end

      request.validationMode = ::AuthorizeNet::API::ValidationModeEnum::LiveMode
      request.validationMode = ::AuthorizeNet::API::ValidationModeEnum::TestMode if @options[:test_mode]

      response = client.create_customer_profile(request)

      error_code = response.messages&.messages&.first&.code
      error_text = response.messages&.messages&.first&.text

      log_response(:create_customer, response)

      return error_text.delete('^0-9') if error_code == 'E00039'

      raise ::Spree::Core::GatewayError, "#{error_code}: #{error_text}" if error_code.present? && error_code != 'I00001'

      response.customerProfileId
    end

    ##
    # Handle response
    #
    # Handles a response after calling authorize net to simplifly
    # reguired ActiveMerchant response object
    def handle_response
      result = yield

      if result.is_a?(TrueClass) && result
        ::ActiveMerchant::Billing::Response.new(true, 'Transaction succeeded')
      elsif result.is_a?(::ActiveMerchant::Billing::Response)
        result
      elsif result.is_a?(Hash)
        ::ActiveMerchant::Billing::Response.new(true, 'Transaction succeeded', {}, result)
      else
        ::ActiveMerchant::Billing::Response.new(false, 'Transaction failed')
      end
    end

    ##
    # Authorize
    #
    # Authorizes a payment to be settled at later time
    def authorize(amount, source, order = {})
      handle_response do
        customer = get_customer(source.customer_id)
        return false if customer.nil?

        log(:authorize, customer)

        request = ::AuthorizeNet::API::CreateTransactionRequest.new

        request.transactionRequest = ::AuthorizeNet::API::TransactionRequestType.new
        request.transactionRequest.amount = amount / 100.0

        request.transactionRequest.profile = ::AuthorizeNet::API::CustomerProfilePaymentType.new
        request.transactionRequest.profile.customerProfileId = customer[:id]
        request.transactionRequest.profile.paymentProfile = ::AuthorizeNet::API::PaymentProfile.new(customer[:payment_profiles][0][:id])

        request.transactionRequest.transactionType = ::AuthorizeNet::API::TransactionTypeEnum::AuthOnlyTransaction
        request.transactionRequest.order = ::AuthorizeNet::API::OrderType.new(order[:order_id])

        response = client.create_transaction(request)
        transaction_id = response.transactionResponse.transId

        log_response(:authorize, response)

        { authorization: transaction_id } if transaction_id.present?
      end
    end

    ##
    # Purchase
    #
    # Purchaes the amount by first authorizing it and then capturing it
    def purchase(amount, source, order)
      handle_response do
        result = authorize(amount, source, order)

        if result.is_a?(::ActiveMerchant::Billing::Response) && result.success? && capture(amount, result.authorization, order).success?
          return result
        end

        false
      end
    end

    ##
    # Capture
    #
    # Captures a previously authoried transaction
    def capture(amount, transaction_id, _)
      handle_response do
        request = ::AuthorizeNet::API::CreateTransactionRequest.new

        request.transactionRequest = ::AuthorizeNet::API::TransactionRequestType.new
        request.transactionRequest.amount = amount / 100.0
        request.transactionRequest.refTransId = transaction_id
        request.transactionRequest.transactionType = ::AuthorizeNet::API::TransactionTypeEnum::PriorAuthCaptureTransaction

        response = client.create_transaction(request)

        log_response(:capture, response)

        response.messages.resultCode == ::AuthorizeNet::API::MessageTypeEnum::Ok
      end
    end

    ##
    # Credit
    #
    # Issues a credit to customer for amount
    def credit(amount, source, transaction_id, _)
      handle_response do
        customer = get_customer(source.customer_id)
        return false if customer.nil?

        log(:credit, customer)

        request = ::AuthorizeNet::API::CreateTransactionRequest.new

        request.transactionRequest = ::AuthorizeNet::API::TransactionRequestType.new
        request.transactionRequest.amount = amount / 100.0

        request.transactionRequest.profile = ::AuthorizeNet::API::CustomerProfilePaymentType.new
        request.transactionRequest.profile.customerProfileId = customer[:id]
        request.transactionRequest.profile.paymentProfile = ::AuthorizeNet::API::PaymentProfile.new(customer[:payment_profiles][0][:id])

        request.transactionRequest.refTransId = transaction_id if transaction_id.present?
        request.transactionRequest.transactionType = ::AuthorizeNet::API::TransactionTypeEnum::RefundTransaction

        response = client.create_transaction(request)

        log_response(:credit, response)

        response.messages.resultCode == ::AuthorizeNet::API::MessageTypeEnum::Ok
      end
    end

    ##
    # Void
    #
    # Voids a previously authed transaction
    def void(transaction_id, _, _)
      handle_response do
        request = ::AuthorizeNet::API::CreateTransactionRequest.new

        request.transactionRequest =  ::AuthorizeNet::API::TransactionRequestType.new
        request.transactionRequest.refTransId = transaction_id
        request.transactionRequest.transactionType = ::AuthorizeNet::API::TransactionTypeEnum::VoidTransaction

        response = client.create_transaction(request)

        log_response(:void, response)

        response.messages.resultCode == ::AuthorizeNet::API::MessageTypeEnum::Ok
      end
    end

    private

    ##
    # Log Response
    #
    # Logs info about a authorize net response
    def log_response(method, response)
      error_code = response.messages&.messages&.first&.code
      error_text = response.messages&.messages&.first&.text

      Rails.logger.info "AuthorizeNetGateway: #{method}: #{error_code}: #{error_text}"
    end

    ##
    # Just logs data
    def log(method, data)
      Rails.logger.info "AuthorizeNetGateway: #{method}: #{data}"
    end
  end
end
